d /run/yunpanel 2770 root yunpanel - -
d /run/yunpanel/ttyd 2770 root yunpanel - -
d /run/yunpanel-phpmyadmin 0750 root yunpanel-phpmyadmin - -
d /run/yunpanel-elfinder 0750 root yunpanel-elfinder - -
